In [1]:
import pandas as pd

cropped = pd.read_csv("/Users/ivantyshchenko/Projects/Python/Neural-Beer/data/meta/cropped_meta.csv")
augmented = pd.read_csv("/Users/ivantyshchenko/Projects/Python/Neural-Beer/data/meta/meta_augmented.csv")

cropped

,image_id,klass,source,source_url,orig_path,orig_filename,width,height,added_at,phash,cropped_path,crop_method,crop_info
0,5c157ab6250368ab3e9947b4a07614644f8e8794,lager,bing,NaN,data/raw/bing/lager/lager_beer_in_glass_at_bar...,000026.jpg,1000,667,2025-10-04T18:00:21Z,cb5be8243036a6e7,data/smart_cropped/5c157ab6250368ab3e9947b4a07...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""cup"",..."
1,f5919fa1605f852dcc8b4d80ac4dc1376c57a8e7,lager,bing,NaN,data/raw/bing/lager/lager_beer_in_glass_at_bar...,000032.jpg,800,533,2025-10-04T18:00:21Z,e69cc99c89939933,data/smart_cropped/f5919fa1605f852dcc8b4d80ac4...,center_square_fallback,"{""method"": ""center_square_fallback"", ""label"": ..."
2,8960123252d5bbd4c251a3d452e955553701228a,lager,bing,NaN,data/raw/bing/lager/lager_beer_in_glass_at_bar...,000033.jpg,1000,667,2025-10-04T18:00:21Z,e499cb9999629a66,data/smart_cropped/8960123252d5bbd4c251a3d452e...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""cup"",..."
3,a50a5b43662152fcd023af3e1600abe6bdf3c17d,lager,bing,NaN,data/raw/bing/lager/lager_beer_in_glass_at_bar...,000019.jpg,1300,1040,2025-10-04T18:00:21Z,adf852842ec37d8a,data/smart_cropped/a50a5b43662152fcd023af3e160...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""cup"",..."
4,0b56d01b6d13c3e2361719466d985296721e4aa8,lager,bing,NaN,data/raw/bing/lager/lager_beer_in_glass_at_bar...,000031.jpg,1000,667,2025-10-04T18:00:21Z,b0c6ce36c9999999,data/smart_cropped/0b56d01b6d13c3e2361719466d9...,center_square_fallback,"{""method"": ""center_square_fallback"", ""label"": ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,d9c10b61fa1b3f33951504c74f2e41d2b83ac5a0,porter,bing,NaN,/Users/ivantyshchenko/Projects/Python/Neural-B...,000032.jpg,626,626,2025-10-05T09:14:14Z,c6cc1933333167ce,data/smart_cropped/d9c10b61fa1b3f33951504c74f2...,center_square_fallback,"{""method"": ""center_square_fallback"", ""label"": ..."
1477,66afb5380aa105bbbf0364be4cc306e86348dfb4,sour,bing,NaN,/Users/ivantyshchenko/Projects/Python/Neural-B...,000007.jpg,943,694,2025-10-05T09:17:13Z,c9b144d6bd693299,data/smart_cropped/66afb5380aa105bbbf0364be4cc...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""wine ..."
1478,9ca409555bd256af367ae57eb7af18174ea5ad2f,sour,bing,NaN,/Users/ivantyshchenko/Projects/Python/Neural-B...,000028.jpg,720,1080,2025-10-05T09:17:13Z,c2bcd926f41186fa,data/smart_cropped/9ca409555bd256af367ae57eb7a...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""wine ..."
1479,e7c225e7e0ac6706d234b4e77ec42ab9e0ddb53d,sour,bing,NaN,/Users/ivantyshchenko/Projects/Python/Neural-B...,000091.jpg,1470,980,2025-10-05T09:18:42Z,90d36f2c90d37b4c,data/smart_cropped/e7c225e7e0ac6706d234b4e77ec...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""sink""..."
1480,df9618ec171441abbed90ff06ba6fe3dbd5a7a06,sour,bing,NaN,/Users/ivantyshchenko/Projects/Python/Neural-B...,000068.jpg,2736,3648,2025-10-05T09:19:35Z,edc4933b1aac8693,data/smart_cropped/df9618ec171441abbed90ff06ba...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""bottl..."

In [2]:
augmented

,image_id,klass,source,source_url,orig_path,orig_filename,width,height,added_at,phash,cropped_path,crop_method,crop_info,aug_id,aug_source,aug_path,aug_params
0,5c157ab6250368ab3e9947b4a07614644f8e8794,lager,bing,NaN,data/raw/bing/lager/lager_beer_in_glass_at_bar...,000026.jpg,1000,667,2025-10-04T18:00:21Z,cb5be8243036a6e7,data/smart_cropped/5c157ab6250368ab3e9947b4a07...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""cup"",...",5c157ab6250368ab3e9947b4a07614644f8e8794_aug1,data/smart_cropped/5c157ab6250368ab3e9947b4a07...,data/augmented/5c157ab6250368ab3e9947b4a076146...,"{""transform_profile"": ""beer_bottle_default_v1""..."
1,5c157ab6250368ab3e9947b4a07614644f8e8794,lager,bing,NaN,data/raw/bing/lager/lager_beer_in_glass_at_bar...,000026.jpg,1000,667,2025-10-04T18:00:21Z,cb5be8243036a6e7,data/smart_cropped/5c157ab6250368ab3e9947b4a07...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""cup"",...",5c157ab6250368ab3e9947b4a07614644f8e8794_aug2,data/smart_cropped/5c157ab6250368ab3e9947b4a07...,data/augmented/5c157ab6250368ab3e9947b4a076146...,"{""transform_profile"": ""beer_bottle_default_v1""..."
2,5c157ab6250368ab3e9947b4a07614644f8e8794,lager,bing,NaN,data/raw/bing/lager/lager_beer_in_glass_at_bar...,000026.jpg,1000,667,2025-10-04T18:00:21Z,cb5be8243036a6e7,data/smart_cropped/5c157ab6250368ab3e9947b4a07...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""cup"",...",5c157ab6250368ab3e9947b4a07614644f8e8794_aug3,data/smart_cropped/5c157ab6250368ab3e9947b4a07...,data/augmented/5c157ab6250368ab3e9947b4a076146...,"{""transform_profile"": ""beer_bottle_default_v1""..."
3,5c157ab6250368ab3e9947b4a07614644f8e8794,lager,bing,NaN,data/raw/bing/lager/lager_beer_in_glass_at_bar...,000026.jpg,1000,667,2025-10-04T18:00:21Z,cb5be8243036a6e7,data/smart_cropped/5c157ab6250368ab3e9947b4a07...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""cup"",...",5c157ab6250368ab3e9947b4a07614644f8e8794_aug4,data/smart_cropped/5c157ab6250368ab3e9947b4a07...,data/augmented/5c157ab6250368ab3e9947b4a076146...,"{""transform_profile"": ""beer_bottle_default_v1""..."
4,f5919fa1605f852dcc8b4d80ac4dc1376c57a8e7,lager,bing,NaN,data/raw/bing/lager/lager_beer_in_glass_at_bar...,000032.jpg,800,533,2025-10-04T18:00:21Z,e69cc99c89939933,data/smart_cropped/f5919fa1605f852dcc8b4d80ac4...,center_square_fallback,"{""method"": ""center_square_fallback"", ""label"": ...",f5919fa1605f852dcc8b4d80ac4dc1376c57a8e7_aug1,data/smart_cropped/f5919fa1605f852dcc8b4d80ac4...,data/augmented/f5919fa1605f852dcc8b4d80ac4dc13...,"{""transform_profile"": ""beer_bottle_default_v1""..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5919,e7c225e7e0ac6706d234b4e77ec42ab9e0ddb53d,sour,bing,NaN,/Users/ivantyshchenko/Projects/Python/Neural-B...,000091.jpg,1470,980,2025-10-05T09:18:42Z,90d36f2c90d37b4c,data/smart_cropped/e7c225e7e0ac6706d234b4e77ec...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""sink""...",e7c225e7e0ac6706d234b4e77ec42ab9e0ddb53d_aug4,data/smart_cropped/e7c225e7e0ac6706d234b4e77ec...,data/augmented/e7c225e7e0ac6706d234b4e77ec42ab...,"{""transform_profile"": ""beer_bottle_default_v1""..."
5920,df9618ec171441abbed90ff06ba6fe3dbd5a7a06,sour,bing,NaN,/Users/ivantyshchenko/Projects/Python/Neural-B...,000068.jpg,2736,3648,2025-10-05T09:19:35Z,edc4933b1aac8693,data/smart_cropped/df9618ec171441abbed90ff06ba...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""bottl...",df9618ec171441abbed90ff06ba6fe3dbd5a7a06_aug1,data/smart_cropped/df9618ec171441abbed90ff06ba...,data/augmented/df9618ec171441abbed90ff06ba6fe3...,"{""transform_profile"": ""beer_bottle_default_v1""..."
5921,df9618ec171441abbed90ff06ba6fe3dbd5a7a06,sour,bing,NaN,/Users/ivantyshchenko/Projects/Python/Neural-B...,000068.jpg,2736,3648,2025-10-05T09:19:35Z,edc4933b1aac8693,data/smart_cropped/df9618ec171441abbed90ff06ba...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""bottl...",df9618ec171441abbed90ff06ba6fe3dbd5a7a06_aug2,data/smart_cropped/df9618ec171441abbed90ff06ba...,data/augmented/df9618ec171441abbed90ff06ba6fe3...,"{""transform_profile"": ""beer_bottle_default_v1""..."
5922,df9618ec171441abbed90ff06ba6fe3dbd5a7a06,sour,bing,NaN,/Users/ivantyshchenko/Projects/Python/Neural-B...,000068.jpg,2736,3648,2025-10-05T09:19:35Z,edc4933b1aac8693,data/smart_cropped/df9618ec171441abbed90ff06ba...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""bottl...",df9618ec171441abbed90ff06ba6fe3dbd5a7a06_aug3,data/smart_cropped/df9618ec171441abbed90ff06ba...,data/augmented/df9618ec171441abbed90ff06ba6fe3...,"{""transform_profile"": ""beer_bottle_default_v1""..."
5923,df9618ec171441abbed90ff06ba6fe3dbd5a7a06,sour,bing,NaN,/Users/ivantyshchenko/Projects/Python/Neural-B...,000068.jpg,2736,3648,2025-10-05T09:19:35Z,edc4933b1aac8693,data/smart_cropped/df9618ec171441abbed90ff06ba...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""bottl...",df9618ec171441abbed90ff06ba6fe3dbd5a7a06_aug4,data/smart_cropped/df9618ec171441abbed90ff06ba...,data/augmented/df9618ec171441abbed90ff06ba6fe3...,"{""transform_profile"": ""beer_bottle_default_v1""..."

In [3]:
full_dataset = pd.concat([cropped, augmented], axis=0, sort=False).reset_index(drop=True)
full_dataset['path'] = (
    full_dataset['aug_path']
    .fillna(full_dataset['cropped_path'])
    .fillna(full_dataset['orig_path'])
)
full_dataset

,image_id,klass,source,source_url,orig_path,orig_filename,width,height,added_at,phash,cropped_path,crop_method,crop_info,aug_id,aug_source,aug_path,aug_params,path
0,5c157ab6250368ab3e9947b4a07614644f8e8794,lager,bing,NaN,data/raw/bing/lager/lager_beer_in_glass_at_bar...,000026.jpg,1000,667,2025-10-04T18:00:21Z,cb5be8243036a6e7,data/smart_cropped/5c157ab6250368ab3e9947b4a07...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""cup"",...",NaN,NaN,NaN,NaN,data/smart_cropped/5c157ab6250368ab3e9947b4a07...
1,f5919fa1605f852dcc8b4d80ac4dc1376c57a8e7,lager,bing,NaN,data/raw/bing/lager/lager_beer_in_glass_at_bar...,000032.jpg,800,533,2025-10-04T18:00:21Z,e69cc99c89939933,data/smart_cropped/f5919fa1605f852dcc8b4d80ac4...,center_square_fallback,"{""method"": ""center_square_fallback"", ""label"": ...",NaN,NaN,NaN,NaN,data/smart_cropped/f5919fa1605f852dcc8b4d80ac4...
2,8960123252d5bbd4c251a3d452e955553701228a,lager,bing,NaN,data/raw/bing/lager/lager_beer_in_glass_at_bar...,000033.jpg,1000,667,2025-10-04T18:00:21Z,e499cb9999629a66,data/smart_cropped/8960123252d5bbd4c251a3d452e...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""cup"",...",NaN,NaN,NaN,NaN,data/smart_cropped/8960123252d5bbd4c251a3d452e...
3,a50a5b43662152fcd023af3e1600abe6bdf3c17d,lager,bing,NaN,data/raw/bing/lager/lager_beer_in_glass_at_bar...,000019.jpg,1300,1040,2025-10-04T18:00:21Z,adf852842ec37d8a,data/smart_cropped/a50a5b43662152fcd023af3e160...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""cup"",...",NaN,NaN,NaN,NaN,data/smart_cropped/a50a5b43662152fcd023af3e160...
4,0b56d01b6d13c3e2361719466d985296721e4aa8,lager,bing,NaN,data/raw/bing/lager/lager_beer_in_glass_at_bar...,000031.jpg,1000,667,2025-10-04T18:00:21Z,b0c6ce36c9999999,data/smart_cropped/0b56d01b6d13c3e2361719466d9...,center_square_fallback,"{""method"": ""center_square_fallback"", ""label"": ...",NaN,NaN,NaN,NaN,data/smart_cropped/0b56d01b6d13c3e2361719466d9...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7400,e7c225e7e0ac6706d234b4e77ec42ab9e0ddb53d,sour,bing,NaN,/Users/ivantyshchenko/Projects/Python/Neural-B...,000091.jpg,1470,980,2025-10-05T09:18:42Z,90d36f2c90d37b4c,data/smart_cropped/e7c225e7e0ac6706d234b4e77ec...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""sink""...",e7c225e7e0ac6706d234b4e77ec42ab9e0ddb53d_aug4,data/smart_cropped/e7c225e7e0ac6706d234b4e77ec...,data/augmented/e7c225e7e0ac6706d234b4e77ec42ab...,"{""transform_profile"": ""beer_bottle_default_v1""...",data/augmented/e7c225e7e0ac6706d234b4e77ec42ab...
7401,df9618ec171441abbed90ff06ba6fe3dbd5a7a06,sour,bing,NaN,/Users/ivantyshchenko/Projects/Python/Neural-B...,000068.jpg,2736,3648,2025-10-05T09:19:35Z,edc4933b1aac8693,data/smart_cropped/df9618ec171441abbed90ff06ba...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""bottl...",df9618ec171441abbed90ff06ba6fe3dbd5a7a06_aug1,data/smart_cropped/df9618ec171441abbed90ff06ba...,data/augmented/df9618ec171441abbed90ff06ba6fe3...,"{""transform_profile"": ""beer_bottle_default_v1""...",data/augmented/df9618ec171441abbed90ff06ba6fe3...
7402,df9618ec171441abbed90ff06ba6fe3dbd5a7a06,sour,bing,NaN,/Users/ivantyshchenko/Projects/Python/Neural-B...,000068.jpg,2736,3648,2025-10-05T09:19:35Z,edc4933b1aac8693,data/smart_cropped/df9618ec171441abbed90ff06ba...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""bottl...",df9618ec171441abbed90ff06ba6fe3dbd5a7a06_aug2,data/smart_cropped/df9618ec171441abbed90ff06ba...,data/augmented/df9618ec171441abbed90ff06ba6fe3...,"{""transform_profile"": ""beer_bottle_default_v1""...",data/augmented/df9618ec171441abbed90ff06ba6fe3...
7403,df9618ec171441abbed90ff06ba6fe3dbd5a7a06,sour,bing,NaN,/Users/ivantyshchenko/Projects/Python/Neural-B...,000068.jpg,2736,3648,2025-10-05T09:19:35Z,edc4933b1aac8693,data/smart_cropped/df9618ec171441abbed90ff06ba...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""bottl...",df9618ec171441abbed90ff06ba6fe3dbd5a7a06_aug3,data/smart_cropped/df9618ec171441abbed90ff06ba...,data/augmented/df9618ec171441abbed90ff06ba6fe3...,"{""transform_profile"": ""beer_bottle_default_v1""...",data/augmented/df9618ec171441abbed90ff06ba6fe3...
7404,df9618ec171441abbed90ff06ba6fe3dbd5a7a06,sour,bing,NaN,/Users/ivantyshchenko/Projects/Python/Neural-B...,000068.jpg,2736,3648,2025-10-05T09:19:35Z,edc4933b1aac8693,data/smart_cropped/df9618ec171441abbed90ff06ba...,detr_object_crop,"{""method"": ""detr_object_crop"", ""label"": ""bottl...",df9618ec171441abbed90ff06ba6fe3dbd5a7a06_aug4,data/smart_cropped/df9618ec171441abbed90ff06ba...,data/augmented/df9618ec171441abbed90ff06ba6fe3...,"{""transform_profile"": ""beer_bottle_default_v1""...",data/augmented/df9618ec171441abbed90ff06ba6fe3...

In [4]:
full_dataset.to_csv('/Users/ivantyshchenko/Projects/Python/Neural-Beer/data/meta/full_dataset.csv', index=False)